import type { ActionKey } from "@/stores/controlsStore";

export const KEY_DISPLAY_MAP: Record<string, string> = {
  ArrowUp: "↑",
  ArrowDown: "↓",
  ArrowLeft: "←",
  ArrowRight: "→",
  Space: "Space",
  Enter: "Enter",
  Escape: "Esc",
  Tab: "Tab",
  Digit0: "0",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  KeyA: "A",
  KeyB: "B",
  KeyC: "C",
  KeyD: "D",
  KeyE: "E",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyI: "I",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  KeyM: "M",
  KeyN: "N",
  KeyO: "O",
  KeyP: "P",
  KeyQ: "Q",
  KeyR: "R",
  KeyS: "S",
  KeyT: "T",
  KeyU: "U",
  KeyV: "V",
  KeyW: "W",
  KeyX: "X",
  KeyY: "Y",
  KeyZ: "Z",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
};

export const ACTION_LABELS: Record<ActionKey, string> = {
  moveUp: "이동 위",
  moveDown: "이동 아래",
  moveLeft: "이동 왼쪽",
  moveRight: "이동 오른쪽",
  interact: "상호작용",
  inventory: "인벤토리",
  equipment: "장비창",
  skillWindow: "스킬 창",
  skill1: "스킬 슬롯 1",
  skill2: "스킬 슬롯 2",
  skill3: "스킬 슬롯 3",
  skill4: "스킬 슬롯 4",
  skill5: "스킬 슬롯 5 (대쉬)",
};

export const SKILL_KEY_GROUPS = [
  ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
  ["Q", "W", "E", "R"],
  ["A", "S", "D", "F"],
] as const;

export const ALL_HOTKEYS = SKILL_KEY_GROUPS.flat();

export const SKILL_CODES = [
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "KeyQ",
  "KeyW",
  "KeyE",
  "KeyR",
  "KeyA",
  "KeyS",
  "KeyD",
  "KeyF",
] as const;
