import type { Class, ClassCardConfig, ClassConfig } from "@/types/class";
import type { SkillState } from "@/types/skill";
import { SKILL_TYPE, DAMAGE_TYPE, TARGET_TYPE } from "@/constants/skill/combat";

export const CLASS = {
  WARRIOR: "warrior",
  ARCHER: "archer",
  MAGE: "mage",
  ROGUE: "rogue",
} as const satisfies Record<string, Class>;

export const CLASS_LABEL: Record<Class, string> = {
  [CLASS.WARRIOR]: "전사",
  [CLASS.ARCHER]: "궁수",
  [CLASS.MAGE]: "마법사",
  [CLASS.ROGUE]: "도적",
};

export const CLASS_COLOR: Record<Class, string> = {
  [CLASS.WARRIOR]: "var(--cls-warrior)",
  [CLASS.ARCHER]: "var(--cls-archer)",
  [CLASS.MAGE]: "var(--cls-mage)",
  [CLASS.ROGUE]: "var(--cls-rogue)",
};

export const CLASS_CARDS: ClassCardConfig[] = [
  {
    id: CLASS.WARRIOR,
    icon: "/images/classes/warrior.png",
    desc: "두꺼운 갑옷과 강인한 체력으로 최전선을 지킨다.",
    stats: { hp: 90, atk: 65, def: 85, spd: 40 },
  },
  {
    id: CLASS.ARCHER,
    icon: "/images/classes/archer.png",
    desc: "빠른 발놀림과 정확한 조준으로 적을 압도한다.",
    stats: { hp: 55, atk: 85, def: 30, spd: 95 },
  },
  {
    id: CLASS.MAGE,
    icon: "/images/classes/mage.png",
    desc: "광대한 마나로 강력한 마법을 구사한다.",
    stats: { hp: 30, atk: 100, def: 15, spd: 70 },
  },
  {
    id: CLASS.ROGUE,
    icon: "/images/classes/rogue.png",
    desc: "날랜 몸놀림과 표창으로 적의 빈틈을 노린다.",
    stats: { hp: 60, atk: 80, def: 40, spd: 90 },
  },
];

export const STAT_BAR_CONFIG = [
  { key: "hp" as const, label: "HP", color: "var(--hp)" },
  { key: "atk" as const, label: "ATK", color: "var(--color-dmg-physical)" },
  { key: "def" as const, label: "DEF", color: "var(--accent)" },
  { key: "spd" as const, label: "SPD", color: "var(--success)" },
];

export const COMMON_SKILLS: SkillState[] = [
  {
    id: "dash",
    key: "5",
    label: "대쉬",
    skillType: SKILL_TYPE.BUFF,
    cooldown: 0.5,
    lastUsed: 0,
    level: 1,
    requiredLevel: 1,
  },
];

export const CLASS_CONFIG: Record<Class, ClassConfig> = {
  [CLASS.WARRIOR]: {
    hp: 150,
    atk: 20,
    def: 5,
    skills: [
      {
        id: "slash",
        key: "1",
        label: "베기",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 0.5,
        lastUsed: 0,
        level: 1,
        requiredLevel: 1,
      },
      {
        id: "charge",
        key: "2",
        label: "돌진",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 8,
        lastUsed: 0,
        level: 1,
        requiredLevel: 10,
      },
      {
        id: "taunt",
        key: "3",
        label: "도발",
        skillType: SKILL_TYPE.BUFF,
        cooldown: 15,
        lastUsed: 0,
        level: 1,
        requiredLevel: 20,
      },
      {
        id: "cataclysm",
        key: "4",
        label: "파멸의 일격",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 25,
        lastUsed: 0,
        level: 1,
        requiredLevel: 30,
      },
      ...COMMON_SKILLS,
    ],
  },
  [CLASS.ARCHER]: {
    hp: 100,
    atk: 22,
    def: 2,
    skills: [
      {
        id: "arrow_shot",
        key: "1",
        label: "화살",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 0.35,
        lastUsed: 0,
        level: 1,
        requiredLevel: 1,
      },
      {
        id: "piercing_arrow",
        key: "2",
        label: "관통화살",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 10,
        lastUsed: 0,
        level: 1,
        requiredLevel: 10,
      },
      {
        id: "backstep",
        key: "3",
        label: "백스텝",
        skillType: SKILL_TYPE.BUFF,
        cooldown: 12,
        lastUsed: 0,
        level: 1,
        requiredLevel: 20,
      },
      {
        id: "explosive_arrow",
        key: "4",
        label: "작렬화살",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.AOE,
        cooldown: 20,
        lastUsed: 0,
        level: 1,
        requiredLevel: 30,
      },
      ...COMMON_SKILLS,
    ],
  },
  [CLASS.MAGE]: {
    hp: 80,
    atk: 30,
    def: 0,
    skills: [
      {
        id: "fireball",
        key: "1",
        label: "화염볼",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.MAGIC,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 0.6,
        lastUsed: 0,
        level: 1,
        requiredLevel: 1,
      },
      {
        id: "ice_spike",
        key: "2",
        label: "빙결창",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.MAGIC,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 10,
        lastUsed: 0,
        level: 1,
        requiredLevel: 10,
      },
      {
        id: "blink",
        key: "3",
        label: "순간이동",
        skillType: SKILL_TYPE.BUFF,
        cooldown: 12,
        lastUsed: 0,
        level: 1,
        requiredLevel: 20,
      },
      {
        id: "black_hole",
        key: "4",
        label: "블랙홀",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.MAGIC,
        targetType: TARGET_TYPE.AOE,
        cooldown: 28,
        lastUsed: 0,
        level: 1,
        requiredLevel: 30,
      },
      ...COMMON_SKILLS,
    ],
  },
  [CLASS.ROGUE]: {
    hp: 90,
    atk: 26,
    def: 1,
    skills: [
      {
        id: "dagger_slash",
        key: "1",
        label: "단검 베기",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 0.3,
        lastUsed: 0,
        level: 1,
        requiredLevel: 1,
      },
      {
        id: "shadow_slash",
        key: "2",
        label: "그림자 베기",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 5,
        lastUsed: 0,
        level: 1,
        requiredLevel: 10,
      },
      {
        id: "smoke_bomb",
        key: "3",
        label: "연막탄",
        skillType: SKILL_TYPE.BUFF,
        cooldown: 14,
        lastUsed: 0,
        level: 1,
        requiredLevel: 20,
      },
      {
        id: "death_dance",
        key: "4",
        label: "죽음의 무도",
        skillType: SKILL_TYPE.ATTACK,
        damageType: DAMAGE_TYPE.PHYSICAL,
        targetType: TARGET_TYPE.SINGLE,
        cooldown: 30,
        lastUsed: 0,
        level: 1,
        requiredLevel: 30,
      },
      ...COMMON_SKILLS,
    ],
  },
};
