import type { Item, ItemType } from "@/types/item";
import { ITEM_TYPE, ITEM_RARITY, ITEM_TRADE } from "@/constants/item";
import { JOB_CLASS } from "@/constants/character";

export const ITEMS = {
  [ITEM_TYPE.WEAPON]: {
    dagger: {
      id: "dagger",
      name: "단검",
      type: ITEM_TYPE.WEAPON,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "🗡️",
      atk: 8,
      def: 0,
      hpBonus: 0,
      requiredLevel: 3,
      requiredClass: [JOB_CLASS.ARCHER, JOB_CLASS.ROGUE],
    },
    steel_sword: {
      id: "steel_sword",
      name: "강철 검",
      type: ITEM_TYPE.WEAPON,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "⚔️",
      atk: 15,
      def: 0,
      hpBonus: 0,
      requiredLevel: 6,
      requiredClass: [JOB_CLASS.WARRIOR, JOB_CLASS.ROGUE],
    },
    iron_sword: {
      id: "iron_sword",
      name: "철제 검",
      type: ITEM_TYPE.WEAPON,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "⚔️",
      atk: 12,
      def: 0,
      hpBonus: 0,
      requiredLevel: 2,
      requiredClass: [JOB_CLASS.WARRIOR, JOB_CLASS.ROGUE],
    },
    deer_horn_sword: {
      id: "deer_horn_sword",
      name: "왕 사슴의 뿔 검",
      type: ITEM_TYPE.WEAPON,
      rarity: ITEM_RARITY.EPIC,
      trade: ITEM_TRADE.UNTRADEABLE,
      icon: "🦌",
      atk: 45,
      def: 5,
      hpBonus: 0,
      requiredLevel: 22,
      requiredClass: [JOB_CLASS.WARRIOR],
    },
    bear_claw_sword: {
      id: "bear_claw_sword",
      name: "곰 발톱 검",
      type: ITEM_TYPE.WEAPON,
      rarity: ITEM_RARITY.EPIC,
      trade: ITEM_TRADE.UNTRADEABLE,
      icon: "🐾",
      atk: 35,
      def: 5,
      hpBonus: 0,
      requiredLevel: 8,
      requiredClass: [JOB_CLASS.WARRIOR],
    },
  },
  [ITEM_TYPE.ARMOR]: {
    leather: {
      id: "leather",
      name: "가죽 갑옷",
      type: ITEM_TYPE.ARMOR,
      rarity: ITEM_RARITY.COMMON,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "🛡️",
      atk: 0,
      def: 2,
      hpBonus: 0,
      requiredLevel: 1,
      requiredClass: [],
    },
    chain: {
      id: "chain",
      name: "사슬 갑옷",
      type: ITEM_TYPE.ARMOR,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "🛡️",
      atk: 0,
      def: 5,
      hpBonus: 0,
      requiredLevel: 4,
      requiredClass: [JOB_CLASS.WARRIOR, JOB_CLASS.ARCHER, JOB_CLASS.ROGUE],
    },
    plate: {
      id: "plate",
      name: "판금 갑옷",
      type: ITEM_TYPE.ARMOR,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "🛡️",
      atk: 0,
      def: 9,
      hpBonus: 0,
      requiredLevel: 7,
      requiredClass: [JOB_CLASS.WARRIOR],
    },
    iron_armor: {
      id: "iron_armor",
      name: "철제 갑옷",
      type: ITEM_TYPE.ARMOR,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "🛡️",
      atk: 0,
      def: 7,
      hpBonus: 0,
      requiredLevel: 3,
      requiredClass: [JOB_CLASS.WARRIOR, JOB_CLASS.ARCHER, JOB_CLASS.ROGUE],
    },
    turtle_shield: {
      id: "turtle_shield",
      name: "거북 등껍질 방패",
      type: ITEM_TYPE.ARMOR,
      rarity: ITEM_RARITY.EPIC,
      trade: ITEM_TRADE.UNTRADEABLE,
      icon: "🐢",
      atk: 0,
      def: 18,
      hpBonus: 0,
      requiredLevel: 15,
      requiredClass: [JOB_CLASS.WARRIOR, JOB_CLASS.ARCHER, JOB_CLASS.ROGUE],
    },
  },
  [ITEM_TYPE.RING]: {
    old_ring: {
      id: "old_ring",
      name: "낡은 반지",
      type: ITEM_TYPE.RING,
      rarity: ITEM_RARITY.COMMON,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "💍",
      atk: 0,
      def: 0,
      hpBonus: 15,
      requiredLevel: 1,
      requiredClass: [],
    },
    ruby_ring: {
      id: "ruby_ring",
      name: "루비 반지",
      type: ITEM_TYPE.RING,
      rarity: ITEM_RARITY.EPIC,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "💍",
      atk: 0,
      def: 0,
      hpBonus: 35,
      requiredLevel: 5,
      requiredClass: [],
    },
    life_ring: {
      id: "life_ring",
      name: "생명의 반지",
      type: ITEM_TYPE.RING,
      rarity: ITEM_RARITY.RARE,
      trade: ITEM_TRADE.TRADEABLE,
      icon: "💍",
      atk: 0,
      def: 0,
      hpBonus: 40,
      requiredLevel: 3,
      requiredClass: [],
    },
  },
} as const satisfies Record<ItemType, Record<string, Omit<Item, "uid">>>;
